### ISSUE TITLE
Using 8bpp within SDL 1.2 will freeze or crash OS upon exit

### ISSUE THREAD

**Issue by gameblabla** [ndless-nspire/Ndless#261]
I noticed this for a while when linking to the new lcd_blit API with SDL 1.2.
When you use the 8bpp mode then quit, it will just crash.

One game where i noticed this was Worship Vector. I also noticed it in other games at the time but forgot whom.
I also debugged the game on PC and found that there was no leaks sooo yeah.

[https://github.com/gameblabla/worship-vector](https://github.com/gameblabla/worship-vector)

[worship.tns.zip](https://github.com/ndless-nspire/Ndless/files/5639612/worship.tns.zip)

Thought using a newer ndless would have fixed this but sadly, it doesn't.

**EDIT**: Oh and yeah, it didn't have the SDL_FreeSurface for its main screen surface, which i added later.
Despite this, and the fact that the game never attempts to allocate memory in the heap, it still crashes.

**EDIT2:**
https://github.com/Vogtinator/nSDL/commit/22fddb3e418627695132fc917c6c029d5245e14a

It seems to me that buffer2 is never being freed. In fact, it seems that even buffer is also seemingly not freed from memory.
However i did just that (made a small patch against it) and it still crashes and reboots the calc unfortunately.

**Comment by Vogtinator** [comment]
This is fixed by https://github.com/Vogtinator/nSDL/pull/1, but I didn't get around to merge it yet.

**Comment by Vogtinator** [comment]
> It seems to me that buffer2 is never being freed. In fact, it seems that even buffer is also seemingly not freed from memory.
However i did just that (made a small patch against it) and it still crashes and reboots the calc unfortunately.

Looks like that's true as well, could you make a PR against the `8ppfix` branch?

**Comment by gameblabla** [comment]
https://github.com/Vogtinator/nSDL/pull/2
I opened a PR here.

**Comment by gameblabla** [comment]
Gave both fixes a try with Worship Vector and unfortunately, it doesn't fix it. It still crashes upon exit even with your fix.
I also tried without my fix and just your PR and same thing.

**Comment by Vogtinator** [comment]
I'm trying to reproduce the issue. I hit a GCC segfault \o/:

```
during IPA pass: icf
In function 'SDL_InstallParachute':
lto1: internal compiler error: Segmentation fault
0xa3539f crash_signal
        ../../download/gcc-10.1.0/gcc/toplev.c:328
0x12a3059 strchr
        /usr/include/string.h:221
0x12a3059 arm_parse_cpu_option_name(cpu_option const*, char const*, char const*, bool)
        ../../download/gcc-10.1.0/gcc/common/config/arm/arm-common.c:349
```

It worked after removing `-march=armv5te` and `-mtune=arm926ej-s`...

**Comment by Vogtinator** [comment]
The built tns works fine in firebird here. I'll try on hardware later.

Can you make sure that you're using the right `libSDL.a` file during linking? You have to override the file in `ndless-sdk/lib`.

**Comment by Vogtinator** [comment]
> The built tns works fine in firebird here. I'll try on hardware later.

Tried it, no crashes during gameplay or exit, did that twice. I did notice a bug though - it doesn't wait for keys to be released, which is most noticable when trying to select the `Return to main menu` option. If you aren't quick enough with releasing the key again, it registers as event in the main menu as well, and you're back in a new game...

**Comment by gameblabla** [comment]
How is this wizadry possible is beyond me, as i was also able to reproduce the crash earlier. As you said, it probably has to do with -march=armv5te -mtune=arm926ej-s. Were you using those flags while playing them ?

**Comment by Vogtinator** [comment]
I can't use your tns with a custom `libSDL.a`, so I need to do a rebuild. That was only possible with removing those flags here, so I had to test without them.

I'm getting a crash on exit of the `link` sample though, so currently I'm looking at that.

**Comment by Vogtinator** [comment]
> I'm getting a crash on exit of the link sample though, so currently I'm looking at that.

That was actually introduced by your commit adding `SDL_Free` and I made that worse by adding the same bug into `NSP_SetVideoMode`... `this->hidden->buffer` is marked as owned by `SDL_VideoSurface`.

I added a hotfix for the crash (https://github.com/Vogtinator/nSDL/commit/f6fe5ecaf41c5a7ac3acfbbd1ea09d76a9e39c0c) and made a PR with a refactor (https://github.com/Vogtinator/nSDL/pull/3). Please have a look as well.

**Comment by gameblabla** [comment]
I suppose this can be closed after the PR gets merged ? It fixed the issues for me.
