### ISSUE TITLE
My Ti nspire CX CAS crashes when loading ndless 4.5

### ISSUE THREAD

**Issue by Cooldude122** [ndless-nspire/Ndless#84]
I click on the installer and it loads for 20 seconds then it just turns off

**Comment by Vogtinator** [comment]
Try again without ndless_resources, does it still crash?
Make sure you didn't do much before opening the installer after booting.
Obviously, make sure you have OS 4.5.

**Comment by Cooldude122** [comment]
I tried it without that and now it only crashes sometimes and other times it just open ndless installer as a blank doc and when I do Ctrl+W it does not say ndless installed

**Comment by Vogtinator** [comment]
Are you _sure_ you have OS 4.5? This is a symptom of having the wrong OS.
You obviously need to have ndless_resources to install ndless successfully.

**Comment by Cooldude122** [comment]
Yes I do have OS 4.5. Then why did you say to install it without ndless_resources if I need it.

**Comment by Vogtinator** [comment]
To find where the issue lies. Do the following after transferring the files to the correct locations:
* Disconnect the calculator
* Press the reset button on the back
* Wait untill it booted
* Directly navigate to the installer and start it

It should work now. If not, do you have many files in the document browser by chance? Do you have nLaunch or nBoot installed? Which HW rev. is your calc?

**Comment by Cooldude122** [comment]
It still does not work for me.  I don't have nBoot or nLaunch. Also what is HW rev. and document browser.

**Comment by geekpersonman** [comment]
HW revision is on the back of your calculator in the form P-####X where # is a number and X is a letter

**Comment by Cooldude122** [comment]
Ok then on the back it says P-0417AA

**Comment by geekpersonman** [comment]
Did ndless work when you had 4.4 installed, or have you only tried on 4.5? That is a fairly recent Hardware revision so there may be compatibility issues with ndless.

**Comment by Cooldude122** [comment]
I did not have OS 4.4 the calculator came with OS 4.5. So I don't know if it works with ndless 4.4

**Comment by geekpersonman** [comment]
Thats interesting, when did you buy it?

**Comment by gonggongjohn** [comment]
I met the same issue when I tried to install ndless on OS 4.5. It works well on OS4.4 before but since I upgrade the system to OS 4.5 I can only find the OS 4.5's system pack on TI official site. Is it possible to degrade the system to OS 4.4 ?

**Comment by Cooldude122** [comment]
I bought it 1 month ago

**Comment by adriweb** [comment]
(FWIW, AA are known, so far, to be from 0217 to 0417, but we've seen an 0217AB as well)

**Comment by Cooldude122** [comment]
What should I do to fix it then? Should I reinstall the is again?

**Comment by adriweb** [comment]
What might matter is if the preloaded OS is actually a bit different. What's the complete version number?

**Comment by Cooldude122** [comment]
It is version 4.5.1180

**Comment by adriweb** [comment]
Ok then IDK. if all the install steps were taken correctly, the problem may lie elsewhere. Not a whole lot of us devs/testers have recent calcs, let alone AA/AB...

**Comment by Cooldude122** [comment]
Is there anyway that I could go back to OS 4.4 to see if ndless works on that OS for my calc

**Comment by bauen1** [comment]
@adriweb I've got a P-0617AA OS 4.4.0.532 and ndless installed just fine.

**Comment by adriweb** [comment]
OK, thanks for the info.

**Comment by geekpersonman** [comment]
and @Cooldude122, From @Vogtinator 's comment earlier, what other files do you have loaded on your nspire besides ndless?

**Comment by Cooldude122** [comment]
The only other files I have are Gravity guy, minesweeper and slime volleyball v.1.0

**Comment by geekpersonman** [comment]
Try with just ndless on there and see if it works
 (After pressing reset on the back again)

**Comment by Cooldude122** [comment]
I pressed reset and ndless still does not work

**Comment by adriweb** [comment]
(Note: it should look like the screenshot on the right, here: https://github.com/ndless-nspire/Ndless#os-450- )

**Comment by Cooldude122** [comment]
What screenshot? I do not see a screenshot

**Comment by adriweb** [comment]
The screenshot in the readme/tutorial...

This one:
![image](https://user-images.githubusercontent.com/660896/32994159-b424d3d4-cd63-11e7-99cc-cb5b13695377.png)

**Comment by Vogtinator** [comment]
Which language does the calc use?

**Comment by geekpersonman** [comment]
Could that affect it?

**Comment by Vogtinator** [comment]
I don't know, it might.

**Comment by Cooldude122** [comment]
Uses English and it also looks like the screenshot

**Comment by calcfreak** [comment]
I am also having the same problem after upgrading to OS4.5 from OS4.4

**Comment by adriweb** [comment]
Is it also P-0617AA or something close?

**Comment by calcfreak** [comment]
P-1016Y

**Comment by adriweb** [comment]
OS+Ndless 4.5 work fine on my rev Y.

**Comment by calcfreak** [comment]
I just updated my OS today, maybe that's why?

**Comment by adriweb** [comment]
I don't know, did you re-download Ndless 4.5, updated the resources and launched the 4.5 installer and not the previous 4.4 one?

**Comment by geekpersonman** [comment]
Have you tried resetting the calculator with the Maintenance menu and downloading the os from scratch?

**Comment by calcfreak** [comment]
I don't know, did you re-download Ndless 4.5, updated the resources and launched the 4.5 installer and not the previous 4.4 one?
Yes. 

Have you tried resetting the calculator with the Maintenance menu and downloading the os from scratch?
No, will doing that delete all my documents?

**Comment by Cooldude122** [comment]
No how do you do that @greekpersonman

**Comment by geekpersonman** [comment]
Force shutdown by pressing the reset button on TI-Nspire CX for 5 or so seconds (the screen shouldn’t turn back on when you release it, otherwise press again for a different amount of time, may take a few tries).
Enter the maintenance menu by turning it on while holding the following keys until half the progress bar:
Doc+Enter+EE then while holding those keys press ON
Select ‘2’ to uninstall the current OS. Reinstall it when asked to. Option ‘4’ (complete format) will also do, but will also delete all your documents.

**Comment by deadmeatpt** [comment]
It surely seems like a symptom of a wrong os though, might be a OS 4.5 variant ndless doesn't support? Like a leaked version or so? (like OS 4.4.0.531(leaked) and 4.4.0.532)?

**Comment by adriweb** [comment]
OS 4.5.1180 is the standard/known one.

**Comment by Ender0715** [comment]
I had the same problem...  I read through the information for install several times then I realized I was putting the endless folder in the "MyLib" folder not the root...  When I ran it from root it installed with no issues.  Hope this helps...

**Comment by TheTeebles** [comment]
I just got a new Nspire today, HW rev is N-1017AC, with OS 4.5.1180 pre-loaded. I Figured I'd drop a line here to let you know that the 4.5 ndless installer does not work, it simply attempts to open, gives a clock in the middle of the screen, and reboots without installing ndless. Any thoughts?

**Comment by adriweb** [comment]
Well this is definitely... "interesting" (also, first time in 10 years that an Nspire has been built in another factory than P, here you say it's "N").
It would be good to have photos of the inside (motherboard etc.) but this isn't such an easy thing to get, unless you're absolutely willing to try and accept potential consequences :P

As I said in the comments, above, that OS version is the standard 4.5 one, so if it really doesn't work, something else (hardware, apparently) is behaving differently. And without physical access to such a new device/revision, it's going to be hard for the ndless developers to fix it...

**Comment by Vogtinator** [comment]
It's probably some slight change in the memory layout which the installer relies on.

Do you have many files on the calc? Can you try to remove/rename `ndless_resources` and try without? If it's still reboots, it's indeed the installer.

**Comment by TheTeebles** [comment]
@Vogtinator - It's a new calculator, ndless was the first file i put onto it. Removing the resources file did not alter the behavior. 

@adriweb - As far as taking it apart, I have a few years of electronic repair experience. I can see to star-headed screws at the bottom of the calculator, on either side of what I'm assuming is a docking port. Possibility exists that one or more may be inside the battery compartment as well, But it's most likely that the case screws are located under the rubber feet. Do I have that about right? If so, I could likely get you some internal photos by the end of next week.

**Comment by Vogtinator** [comment]
> @Vogtinator - It's a new calculator, ndless was the first file i put onto it. Removing the resources file did not alter the behavior.

Ok. Can you try a slightly altered installer?

[ndless_installer_4.5.0.zip](https://github.com/ndless-nspire/Ndless/files/1682650/ndless_installer_4.5.0.zip)

If that's not it, it might be the address on the stack which it references. It's not too unlikely that it changed. Unfortunately this would

a) Not be easy to find without having ndless on the calc already
b) Not be easy to fix as it would break all other HW revs.

**Comment by adriweb** [comment]
> @adriweb - As far as taking it apart, I have a few years of electronic repair experience. I can see two star-headed screws at the bottom of the calculator, on either side of what I'm assuming is a docking port. Possibility exists that one or more may be inside the battery compartment as well, But it's most likely that the case screws are located under the rubber feet. Do I have that about right? If so, I could likely get you some internal photos by the end of next week.

It's not so easy, actually. @critor made a tutorial for opening recent Nspire CX (assuming it's still valid for AC!) https://tiplanet.org/forum/viewtopic.php?f=16&t=20874#p225376
Ask for help if needed, it'd be a shame to break stuff!

**Comment by Vogtinator** [comment]
Actually, can you download the system logs from the device? Those may contain helpful information about the differences.

**Comment by TheTeebles** [comment]
With that modified installer, the issue persists. Clock shows up in the
middle of the screen, then it reboots. Out of my personal curiosity, I
tried it with and without the .cfg, with no change in behavior. Any sort of
bench debugger that I can use to find these addresses? i noticed there was
an on-calc one but... that needed ndless.

Also, I appreciate you taking the time to help me with all this.

**Comment by TheTeebles** [comment]
@Vogtinator - Logs pulled directly from it:

[NspireLogs.zip](https://github.com/ndless-nspire/Ndless/files/1682732/NspireLogs.zip)

@adriweb - removing that screen frame would not be easy. Looks like it's held with adhesive of some sort, which in my experience is normally removed easier with heat. I'm not sure what said heat would do to the buttons. I also don't know how much that adhesive degrades upon removal, meaning replacing the frame wouldn't likely be fun either.

**Comment by Vogtinator** [comment]
> @Vogtinator - Logs pulled directly from it:

Thanks! I'll try to have a look at it when I've got time.

**Comment by Vogtinator** [comment]
Ok, I've got an idea. Please try the attached installer. If that doesn't work, I'll dig a bit deeper into the logs.

[ndless_installer_4.5.0.zip](https://github.com/ndless-nspire/Ndless/files/1691991/ndless_installer_4.5.0.zip)

**Comment by RyanosMob** [comment]
I've had the same problem as everyone here except i upgraded from 4.3 to 4.5, I tried that other launcher that Vogtinator posted and nothing changed, still the clock in the middle and it restarts

**Comment by vh8597** [comment]
i tried everything @Vogtinator vogtinator but it still crashes

**Comment by vh8597** [comment]
ive also tried to downgrade my os on my calc but doesnt seem to work @Vogtinator

**Comment by adriweb** [comment]
@RyanosMob @vh8597 what's your Nspire's revision/datecode? It's the few letters/digits on the back, next to the serial number on the right. Latest we've seen is apparently `N-1017AC`.

**Comment by vh8597** [comment]
@adriweb ill check tommrrow i left it at school

**Comment by Vogtinator** [comment]
@vh8597 Please also upload NspireLogs.zip.

I should have some more time this weekend to try to reproduce the issue with the included information.

**Comment by vh8597** [comment]
im new to this so how do i get the NspireLogs.zip @Vogtinator

**Comment by Vogtinator** [comment]
Take any tool which is able to download files from the nspire. It's in the root directory.

**Comment by vh8597** [comment]
@Vogtinator how is it going so far btw i dont understand any of that sorry

**Comment by adriweb** [comment]
@ Anyone having a calc where it doesn’t work, what’s your boot1 version by the way? (Home > settings > about)

**Comment by MiniLevy** [comment]
I'm having the same problem with my new Cas Calculator. The details of it is TI-Inspire CX CAS 4.5.0.
I'm getting the clock as soon as i press the installer then it shuts off for 20-30 secs and returns to main screen. i've downloaded the Ndless 4.5.0 and the resources and cfg. along with Gpsp launcher and resources and game config and gba bios with pokemon Ruby gba tns and it won't work.

**Comment by adriweb** [comment]
What’s the date code + hardware revision on the back ? Something like “N-1017AC”

**Comment by Vogtinator** [comment]
Please copy both of the files in the zip archive to your calc and reboot it twice (make sure to close any open documents and clear your scratchpad before rebooting).
Then try both files and report what they do.

If possible, attach NspireLogs.zip after the tries if both of them crashed.

[installers.zip](https://github.com/ndless-nspire/Ndless/files/1725458/installers.zip)

**Comment by alexsko99** [comment]
Just another confirmation that it no longer works on the TI-Inspire CX CAS 
Version 4.5.0.1180
P-0417AA 
I updated from 4.4 to 4.5 and it stopped working  so based on the earlier posts i would think
it's a compatibility error on the installation process.

**Comment by Vogtinator** [comment]
@alexsko99 please follow the instructions in the previous comment.

Just writing "It stopped working" doesn't help much...

**Comment by phyllocrania** [comment]
> 
I just got a new Nspire today, HW rev is N-1017AC, with OS 4.5.1180 pre-loaded. I Figured I'd drop a line here to let you know that the 4.5 ndless installer does not work, it simply attempts to open, gives a clock in the middle of the screen, and reboots without installing ndless. Any thoughts?
--

I have a revision AB and mine reboots on first run, try right after the reboot running installer again

**Comment by kforsberg42** [comment]
i too am having trouble with 4.5, i have the 4.5 installer, a 4.5.1180 calc, reasources, and cfg, anything im doing wrong, Thanks

**Comment by vh8597** [comment]
@Vogtinator have you come up with anything recently

**Comment by Vogtinator** [comment]
I'm still waiting for feedback on https://github.com/ndless-nspire/Ndless/issues/84#issuecomment-365725825.

**Comment by critor** [comment]
We've got other reports of correct Ndless installations on HW-AC. So it's not that it doesn't work, which would have been much simpler to address.

**Comment by adriweb** [comment]
The “normal” installer doesn’t work as-is as per all reports, but the installation through another process (boot loader) or through one of the modified installers shared here in the comments does/may, as the installation procedure differs (a bit or greatly, depending on what it is).
People just need to (test and) give more feedback about the modified installers here for the case to be closed.
Or well, we could try getting our own hands on an AC, but that’s a bit harder...

**Comment by danielhidra** [comment]
I'm also having the same issue with ndless version 4.5 . HW rev is P-021 2D

**Comment by critor** [comment]
Yes, many people. :)

**Comment by alexsko99** [comment]
Just an update @Vogtinator 

followed what you suggested above and then  re-installed the original Ndless except this time it installed perfectly and seems to work just fine. Thanks

**Comment by ElMaimon3** [comment]
@Vogtinator should I run your custom installers from root or from the ndless folder?

**Comment by Vogtinator** [comment]
> @Vogtinator should I run your custom installers from root or from the ndless folder?

Like any other installer. It shouldn't matter, as long as `ndless_resources.tns` is inside `ndless`.

**Comment by Loofy101** [comment]
I had the same issue but now it works. The ndless installer and resources I got from a YouTube tutorial which provided the files for 4.5. Those didn't work. I found this thread and was going to use the new modified installer but I tried something else. I recently downloaded ndless 4.5 from the website and although it is the same from the YouTube tut, this one worked fine for me. So try a fresh install from the website if people got theirs from an outdated source. I am using ti nspire cx CAS. Hope this helps somebody.

**Comment by cydia2020** [comment]
Having the same problem with P-0815V HW here, the first attempt after updating worked, I opened the file and it installed without me even pressing Ctrl and W, but afterwards it simply shows a clock in the middle of the display and stuck after a few seconds.

**Comment by feliceconfuso** [comment]
I have the nspire cx calculator with SO 4.5.0.1180. I tried to install all possible versions of nless (3.6 / 3.9 / 3.91 / 4.2 / 4.3 / 4.4). With the 4.5 comes out the watch then a white screen and does not install. I tried to remove "resource" and reset. Nothing .... Do you have any suggestions? Thank you

**Comment by Vogtinator** [comment]
@feliceconfuso: Does it go to the home screen and nothing happens or does it reboot?

**Comment by PabloGaleano88** [comment]
When I tried to install Ndless , a white windows appears and nothing happend, I read that i must place the ndless installer into a folder named "ndless" (top-level). I tried that and It worked.

**Comment by InfiniteBlaze** [comment]
This ^. Had many of the problems above until I placed the 3 files (installer, cfg, and resources) in a file named "ndless" on my calculator. Even though I had all the same files throughout, having them in the folder worked and got "ndless installed!" at the top after waiting 20-30 seconds. Try this if you don't have them organized in a file this way.

**Comment by Vogtinator** [comment]
That's literally what's described in the official installation guide...

Which guide did you use for installation? It's apparently wrong.

**Comment by rayzliao8787** [comment]
Hi @Vogtinator I know it's been a while, but mine doesn't seem to work. I tried all of the steps you gave us, but it reboots every time. The Installers zip file you gave us also made the calculator reboot. I don't know what's the problem, can you please help me? Also, can you explain how to get a NspireLogs.zip file? I don't really understand. Sorry... :P

**Comment by rayzliao8787** [comment]
My calculator is a TI Nspire CX with a 4.5.0.1180 OS

**Comment by sirshishkabob** [comment]
^ Same as rayzliao8787   Been looking for a solution and trying everything for an hour or so

**Comment by sirshishkabob** [comment]
Now it freezes whenever I launch the installer

**Comment by sirshishkabob** [comment]
if I remove ndless_resource, it doesn't freeze and just restarts

**Comment by Itonemediatech** [comment]
you got add the .cfg whitch is easy to delete when cleaning out the folder for port.

**Comment by satyamedh** [comment]
can someone here confirm if this is still an issue with r2020?
